# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170520_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Redactor', 'verbose_name_plural': 'Redactores'},
        ),
    ]
