# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('sub_title', models.CharField(max_length=600, verbose_name='Copete')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/image')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
        ),
    ]
